spring.application.name: DrukujParagon
server.port: 8080

paragon:
  printerName: POS-58-Series
  maxCharsInLine: 32
  title: "Polecam - Joanna Plebaniak"
  qrIntro: "Zapraszam na stronę:"
  qrData: "https://www.facebook.com/polecam.joanna.plebaniak"
